# Generated by Django 5.1.5 on 2025-02-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room')], max_length=100)),
                ('pricePerNight', models.IntegerField(default=1500)),
                ('currency', models.CharField(choices=[('inr', 'INR'), ('usd', 'USD')], default='inr', max_length=10)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
