# Generated by Django 5.1.6 on 2025-02-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.AddField(
            model_name="room",
            name="place",
            field=models.CharField(default="", max_length=100),
        ),
    ]
