# Generated by Django 5.1.6 on 2025-02-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0002_remove_room_currency_remove_room_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="place",
        ),
    ]
