# Generated by Django 5.1.6 on 2025-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0003_remove_room_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="place",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
