# Generated by Django 5.1.6 on 2025-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0004_room_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="roomImage",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
