# Generated by Django 5.1.6 on 2025-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0006_alter_room_roomimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="roomImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="staticFiles/uploads"
            ),
        ),
    ]
