# Generated by Django 5.1.6 on 2025-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0007_alter_room_roomimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="Description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
