# Generated by Django 4.0.6 on 2025-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('premium', 'premium')], max_length=100),
        ),
    ]
