# Generated by Django 4.0.6 on 2025-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Standard', 'standard'), ('Deluxe', 'deluxe'), ('Premium', 'premium')], max_length=100),
        ),
    ]
