# Generated by Django 4.0.6 on 2025-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], max_length=100),
        ),
    ]
