# Generated by Django 4.0.6 on 2025-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_alter_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(blank=True, default='', max_length=100)),
                ('des_city', models.CharField(blank=True, default='', max_length=100)),
                ('dep_city', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
                ('bus_type', models.CharField(choices=[('standard', 'Standard'), ('ac', 'A/C')], max_length=100)),
                ('seatsRemaining', models.IntegerField()),
            ],
        ),
    ]
