# Generated by Django 4.0.6 on 2025-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='buses',
            name='busImage',
            field=models.ImageField(blank=True, null=True, upload_to='staticFiles/uploads/buses'),
        ),
    ]
