# Generated by Django 4.0.6 on 2025-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_buses_description_buses_busimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
                ('tourImage', models.ImageField(blank=True, null=True, upload_to='staticFile/uploads/tours')),
            ],
        ),
    ]
