# Generated by Django 4.0.6 on 2025-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0017_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tourImage',
            field=models.ImageField(blank=True, null=True, upload_to='staticFiles/uploads/tours'),
        ),
    ]
