# Generated by Django 4.0.6 on 2025-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_alter_tour_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
