# Generated by Django 4.0.6 on 2025-05-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0019_tour_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_airport', models.CharField(blank=True, default='', max_length=100)),
                ('des_airport', models.CharField(blank=True, default='', max_length=100)),
                ('departure_date', models.DateField()),
            ],
        ),
    ]
