# Generated by Django 4.0.6 on 2025-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0020_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
