# Generated by Django 4.0.6 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0021_remove_flight_departure_date_flight_flight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticFiles/uploads/flights'),
        ),
    ]
