# Generated by Django 4.0.6 on 2025-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0022_flight_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
