# Generated by Django 4.0.6 on 2025-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0024_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='endingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='startingDate',
            field=models.DateField(null=True),
        ),
    ]
