# Generated by Django 4.0.6 on 2025-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0025_tour_endingdate_tour_startingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='endingDate',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='startingDate',
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
