# Generated by Django 4.0.6 on 2025-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0026_remove_tour_endingdate_remove_tour_startingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomsRemaining',
            field=models.IntegerField(null=True),
        ),
    ]
