# Generated by Django 4.0.6 on 2025-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0028_roomtype_remove_room_type_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ManyToManyField(blank=True, to='tourism.roomtype'),
        ),
    ]
