# Generated by Django 4.0.6 on 2025-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0029_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('premium', 'premium')], max_length=100),
        ),
    ]
