# Generated by Django 4.0.6 on 2025-05-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_hotelbookings_type'),
        ('tourism', '0030_alter_roomtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
