# Generated by Django 4.0.6 on 2025-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0031_remove_room_type_delete_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('premium', 'premium')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ManyToManyField(blank=True, to='tourism.roomtype'),
        ),
    ]
