# Generated by Django 4.0.6 on 2025-05-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0032_roomtype_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
    ]
