# Generated by Django 5.2.1 on 2025-05-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0033_remove_room_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoomType",
        ),
    ]
