# Generated by Django 5.2.1 on 2025-06-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0034_delete_roomtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="adventures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="tour",
            name="adventure",
            field=models.ManyToManyField(to="tourism.adventures"),
        ),
    ]
