# Generated by Django 5.2.1 on 2025-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0035_adventures_tour_adventure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="adventure",
            field=models.ManyToManyField(blank=True, to="tourism.adventures"),
        ),
    ]
