# Generated by Django 5.2.1 on 2025-06-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0036_alter_tour_adventure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tour",
            old_name="adventure",
            new_name="available_adventures",
        ),
    ]
