# Generated by Django 4.0.6 on 2025-03-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0008_room_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_name', to='tourism.room')),
                ('pricePerNight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cost', to='tourism.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
