# Generated by Django 4.0.6 on 2025-03-16 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_hotelbookings_delete_roombookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookings',
            name='checkInDate',
            field=models.DateField(default=datetime.date(2025, 3, 16)),
        ),
        migrations.AddField(
            model_name='hotelbookings',
            name='checkOutDate',
            field=models.DateField(default=datetime.date(2025, 3, 17)),
        ),
    ]
