# Generated by Django 4.0.6 on 2025-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_hotelbookings_checkindate_hotelbookings_checkoutdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbookings',
            name='checkInDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbookings',
            name='checkOutDate',
            field=models.DateField(),
        ),
    ]
