# Generated by Django 4.0.6 on 2025-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_hotelbookings_checkindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookings',
            name='bookedFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbookings',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
