# Generated by Django 4.0.6 on 2025-03-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_hotelbookings_bookedfor_hotelbookings_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbookings',
            old_name='bookedFor',
            new_name='totalPayable',
        ),
    ]
