# Generated by Django 4.0.6 on 2025-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_bookedfor_hotelbookings_totalpayable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookings',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
