# Generated by Django 4.0.6 on 2025-05-09 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0027_room_roomsremaining'),
        ('bookings', '0007_hotelbookings_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('bookingDate', models.DateField()),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('totalPayable', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tourism.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTour', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
