# Generated by Django 4.0.6 on 2025-05-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0028_roomtype_remove_room_type_room_type'),
        ('bookings', '0008_tourbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookings',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='tourism.roomtype'),
        ),
    ]
