# Generated by Django 4.0.6 on 2025-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_hotelbookings_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbookings',
            name='type',
        ),
    ]
