# Generated by Django 4.0.6 on 2025-05-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0030_alter_roomtype_name'),
        ('bookings', '0010_remove_hotelbookings_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookings',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.roomtype'),
        ),
    ]
