# Generated by Django 4.0.6 on 2025-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_hotelbookings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbookings',
            name='type',
            field=models.CharField(blank=True, choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('premium', 'premium')], max_length=100, null=True),
        ),
    ]
