# Generated by Django 5.2.1 on 2025-05-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_alter_hotelbookings_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelbookings",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hotelbookings",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
