# Generated by Django 5.2.1 on 2025-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_tourbookings_name"),
        ("tourism", "0037_rename_adventure_tour_available_adventures"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourbookings",
            name="adventures",
            field=models.ManyToManyField(blank=True, to="tourism.adventures"),
        ),
    ]
